import 'package:dart_mappable/dart_mappable.dart';
import 'package:expancetracker/core/utils/json_converters/icondata_converters.dart';
import 'package:flutter/material.dart' show Icons;
import 'package:flutter/widgets.dart' show IconData;

// Will be generated by dart_mappable
part 'transaction_category.mapper.dart';

@MappableClass(includeCustomMappers: [IconDataMapper()])
class TransactionCategory with TransactionCategoryMappable {
  const TransactionCategory({
    required this.id,
    required this.title,
    this.totalAmount = 0.0,
    required this.color,
    required this.status,
    @IconDataMapper() required this.icon,
  });

  final String id;
  final String title;
  final double totalAmount;
  final int color;
  final TransactionStatus status;

  final IconData icon;

  static final fromMap = TransactionCategoryMapper.fromMap;
  static final fromJson = TransactionCategoryMapper.fromJson;

  factory TransactionCategory.home() => const TransactionCategory(
    id: 'home',
    title: 'Home',
    totalAmount: 0.0,
    color: 0xFF4CAF50,
    status: TransactionStatus.income,
    icon: Icons.home,
  );
  factory TransactionCategory.food() => const TransactionCategory(
    id: 'food',
    title: 'Food',
    totalAmount: 0.0,
    color: 0xFF2196F3,
    status: TransactionStatus.expense,
    icon: Icons.fastfood,
  );
  factory TransactionCategory.shopping() => const TransactionCategory(
    id: 'shopping',
    title: 'Shopping',
    totalAmount: 0.0,
    color: 0xFF9C27B0,
    status: TransactionStatus.expense,
    icon: Icons.shopping_cart,
  );
}

@MappableEnum()
enum TransactionStatus { income, expense }
