// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9PeoihJI-sVzvn3Ju7-GB5VpcACtWeYo',
    appId: '1:766668200983:web:3dba8cfc977fe4d0181052',
    messagingSenderId: '766668200983',
    projectId: 'deu-expanse-tracker',
    authDomain: 'deu-expanse-tracker.firebaseapp.com',
    storageBucket: 'deu-expanse-tracker.appspot.com',
    measurementId: 'G-9EL05LRH8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCes7RWqQehu0HjLwXO-zNPd0q7f8yLVX8',
    appId: '1:766668200983:android:8342100a3c99e9c7181052',
    messagingSenderId: '766668200983',
    projectId: 'deu-expanse-tracker',
    storageBucket: 'deu-expanse-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1D8Wj2EFB75AIbMfN5ZCNWBBUxJDwDhM',
    appId: '1:766668200983:ios:4b34751349b68021181052',
    messagingSenderId: '766668200983',
    projectId: 'deu-expanse-tracker',
    storageBucket: 'deu-expanse-tracker.appspot.com',
    iosBundleId: 'com.example.expancetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1D8Wj2EFB75AIbMfN5ZCNWBBUxJDwDhM',
    appId: '1:766668200983:ios:4b34751349b68021181052',
    messagingSenderId: '766668200983',
    projectId: 'deu-expanse-tracker',
    storageBucket: 'deu-expanse-tracker.appspot.com',
    iosBundleId: 'com.example.expancetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9PeoihJI-sVzvn3Ju7-GB5VpcACtWeYo',
    appId: '1:766668200983:web:d9993252cf5ad1e0181052',
    messagingSenderId: '766668200983',
    projectId: 'deu-expanse-tracker',
    authDomain: 'deu-expanse-tracker.firebaseapp.com',
    storageBucket: 'deu-expanse-tracker.appspot.com',
    measurementId: 'G-6XX9NDMMQ2',
  );
}
