name: "Build and Deploy Firebase Distribution"

on:
  push:
    branches:
      - main

jobs:
  succesfull_apk_build:
    runs-on: ubuntu-latest # ubuntu os system
    timeout-minutes: 30
    
    steps:
    - name: Clone & Setup Repository
      uses: actions/checkout@v6


    - name: Flutter SDK Setup
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version-file: pubspec.yaml # path to pubspec.yaml

    - run: flutter --version
    
    - name: Generate Build Files
      run: |
        dart run build_runner clean
        dart run build_runner build --delete-conflicting-outputs
          
      
    - name: Build Flutter App
      run: |
        flutter clean
        flutter build apk --release  --no-tree-shake-icons 
        
    
    
