name: "Build and Deploy Firebase Distribution"

on:
  push:
    branches:
      - main

jobs:
  distribution_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: SETUP JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'


    - name: SETUP Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Build Flutter App
      run: |
        flutter clean
        flutter build apk --release  --no-tree-shake-icons 
        
    
    